### ISSUE TITLE
does this support nativescript core (js, ts)?

### ISSUE THREAD

**Issue by csaggo** [nativescript-community/ui-drawer#13]
sorry this might be a stupid question, but i am only seeing examples for vue, angular, svelte but not the usual core demo.

**Comment by trevortos** [comment]
I too would like to see a JS demo.

**Comment by farfromrefug** [comment]
@csaggo @trevortos  yes it should. Try to use it like any other component/plugin
Namespace being @nativescript-community/ui-drawer. And the component name being drawer

**Comment by keerl** [comment]
If someone gets it working could you send me a link to the code? I could add a vanilla js/ts demo to the repo since it seems there is interest in that.

**Comment by Whip** [comment]
Seriously, do you despise vanilla js so much that you didn't even take its name in the readme? Vue and svelte people should understand a js demo but the opposite is not true.

**Comment by farfromrefug** [comment]
@Whip That is not a nice way to comment on an Open Source projet. Every contributor here work on this on its free time to help the community. If you really think vanilla is missing, why dont you contribute ?
Makes me sad to see people like you...

**Comment by Whip** [comment]
I didn't mean to hurt your feelings. Unfortunately I can't contribute, I'm a web developer and I picked up Nativescript few years ago (around NS4) exactly because they claimed you wouldn't have to learn a new language to develop apps. So I feel bad when I see an important plugin from nativescript has no vanilla js support. I'm sorry.

**Comment by Fabiyo-90** [comment]
farfromrefug, really we must apologize, far from our intention to cause you any harm. I am currently entering to test https://github.com/rigor789/nativescript-vue-next, and would like to load your plugin. It would have been easier if there was a way to do it via vanillaJs. Anyway, I think I need some help from you or some direction I can follow.

And thank you again for this work

**Comment by farfromrefug** [comment]
@Fabiyo-90 look at the vue index file. should show you how to do it

**Comment by Fabiyo-90** [comment]
If I don't succeed, I will come back to you, I would like to become a contributor too

**Comment by Fabiyo-90** [comment]
In my file main.ts
`import { 
  createApp, 
  h, 
  registerElement 
} from 'nativescript-vue';
import { createPinia } from 'pinia';
import { install as InstallUIDrawer  } from '@nativescript-community/ui-drawer';

// Components
import AppComponent from './components/App.vue';

// All init
InstallUIDrawer();

// Register new elements 
registerElement('RootLayout', () => require('@nativescript/core').RootLayout, { NSVViewFlags: 4 /* LAYOUT_VIEW */ });
registerElement('Drawer', () => require('@nativescript-community/ui-drawer').Drawer, {
  component: require('@nativescript-community/ui-drawer/vue/component')
});

const App = createApp({
  render: () => h('frame', [h(AppComponent)]),
});

App.use(createPinia());

App.start()`

And in my file App.vue 
`<template>
    

    <Page>
        <ActionBar>
            <Label text="Basic Drawer" />
        </ActionBar>

        <Drawer
            ref="drawer"
            :gestureHandlerOptions="{
                failOffsetYStart: -10,
                failOffsetYEnd: 10
            }"
        >
            <GridLayout ref="leftDrawer" class="drawer" width="300" backgroundColor="blue" rows="auto, *">
                <StackLayout backgroundColor="#eeeeee" padding="25">
                    <GridLayout columns="80, *" height="100">
                        <StackLayout col="0" class="avatar">
                            <Label text="JS" />
                        </StackLayout>
                    </GridLayout>

                    <StackLayout>
                        <Label text="John Smith" fontWeight="bold" />
                        <Label text="john.smith@example.com" />
                    </StackLayout>
                </StackLayout>
                
            </GridLayout>

            <StackLayout ref="mainContent" backgroundColor="yellow" 
                verticalAlignment="center" horizontalAlignment="center">
                <Button @tap="onOpenDrawer()" text="Open Drawer" width="250" marginTop="25" />
            </StackLayout>
        </Drawer>
    </Page>
</template>

<script lang="ts">
  import { defineComponent, ref } from 'nativescript-vue';
  import { UseCounterStore } from '~/store/counter';

  const actions = {
    tapOnButton(myStore: any) {
      myStore.increment();
    }
  };

  export default defineComponent({
    propos: [],

    components: {
      
    },
    
    setup() {
      let myStore = UseCounterStore();
      let drawer = ref();

      return {
        message: "Hello world !",
        actions,
        myStore,
        onOpenDrawer() {
          drawer.open('left');
        },

        onCloseDrawer() {
          drawer.close('left');
        }
      }
    }
  });

</script>

<style scoped>
</style>
`
The result, I have nothing, what is not correct ?
<img width="659" alt="ns_drawer" src="https://user-images.githubusercontent.com/26508533/175421133-3b7771ed-844c-4b32-906a-01ab023883d2.png">

**Comment by farfromrefug** [comment]
@Fabiyo-90 you are missing the ~mainContent

**Comment by farfromrefug** [comment]
@Fabiyo-90 you are using ref for mainContent which I don't think is what we want. we want ~mainContent

**Comment by Fabiyo-90** [comment]
OK ! 
I'll try to see and test if this is supported in nativescript-vue-next... there isn't any supporting documentation yet so I'm trying quite a few things. I'll see what fits best for it

**Comment by farfromrefug** [comment]
@Fabiyo-90 I understand. wondering if there are N components which need ~ and thus that Igor would have implemented. (never looked at vue 3)

**Comment by Fabiyo-90** [comment]
@farfromrefug
The ~ is not working into nativescript-vue-next, I try to recreate the component, it's necessary replace the "~" with "ref", I'll try to see if it works correctly

**Comment by farfromrefug** [comment]
@Fabiyo-90 you don't care about nativedrawer. it is a pattern we use in NVue.
now don't think you ll be able to do it using ref. the thing is that main content needs to be passed to the drawer as a property. this is what ~ is for. did you ask Igor?

**Comment by Fabiyo-90** [comment]
I wrote in the discord (https://discord.com/channels/603595811204366337/606457523574407178/989857337680494602) sending the link hoping he will see this.
I understand why I had an error where "NativeDrawer" was not recognized, I was going to see how to easily integrate it by recreating a "Drawer" component

**Comment by Fabiyo-90** [comment]
I wanted to try otherwise by wanting to integrate it but I'm blocked. There are a lot of things that are not yet supported with nativescript-vue-next, I wanted to work around that with nativescript-vue-next's own methods but hey, I haven't progressed. I believe an example with Vanilla would have been great so in some cases, users of frontend frameworks would have known how to integrate it themselves. I will continue to search in the meantime to learn the inner workings of the nativescript framework as well as its integration with vuejs 3
