### ISSUE TITLE
Items inside mainContent become unresponsive when rotated on iOS

### ISSUE THREAD

**Issue by hendrickson-tyler** [nativescript-community/ui-drawer#21]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Running into a strange issue. Essentially, if I start the app in portrait mode and then rotate to landscape while on a view with a drawer, everything inside of `mainContent` becomes grayed out and unresponsive. If I open and close the drawer while in this state, it fixes it (even after subsequent rotations). Issue then comes back once the app is restarted.

Curiously, if I start the app in landscape, the issue never presents itself.

Here's a demonstration of that in my app:
![Simulator Screen Recording - iPhone 14 Pro - 2023-04-08 at 19 15 51](https://user-images.githubusercontent.com/6372535/230749317-c7dbb0a1-903a-40bb-a0ce-72fb88b0ae17.gif)

This appears to have been introduced in v0.1.7 of the plugin. Reverting to v0.1.6 eliminates the issue entirely.

### Which platform(s) does your issue occur on?
Only iOS (tested on iOS 16.4)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.5.2
- Cross-platform modules: 8.5.0
- Runtime(s): 8.5.1 (iOS)
- Plugin(s):
```json
"dependencies": {
    "@nativescript-community/ui-checkbox": "^2.0.8",
    "@nativescript-community/ui-drawer": "^0.1.10",
    "@nativescript-community/ui-pulltorefresh": "^2.5.3",
    "@nativescript/angular": "^15.2.0",
    "@nativescript/animated-circle": "^1.1.7",
    "@nativescript/camera": "^5.0.15",
    "@nativescript/core": "^8.5.0",
    "@nativescript/firebase-auth": "^3.0.0",
    "@nativescript/firebase-core": "^3.0.0",
    "@nativescript/firebase-crashlytics": "^3.0.0",
    "@nativescript/firebase-firestore": "^3.0.0",
    "@nativescript/firebase-messaging": "^3.0.0",
    "@nativescript/firebase-performance": "^3.0.0",
    "@nativescript/firebase-storage": "^3.0.0",
    "@nativescript/imagepicker": "^1.0.10",
    "@nativescript/iqkeyboardmanager": "^2.1.1",
    "@nstudio/ui-collectionview": "^4.0.70"
  },
  "devDependencies": {
    "@nativescript/android": "^8.5.0",
    "@nativescript/ios": "8.5.1",
    "@nativescript/types": "^8.5.0",
    "@nativescript/webpack": "^5.0.14"
  }
```
### Please, tell us how to recreate the issue in as much detail as possible. 
See StackBlitz repo example below.

I'm not sure if it's a NativeScript Preview thing, but the issue does not present itself on first run. You will have to update a `Label` or something to trigger a refresh. You'll notice that the font size becomes bigger (new accessibility font scaling stuff in 8.5.0, unrelated, I think) when the issue shows up.

Then it's simply:
1. Rotate device to landscape
2. Cannot scroll anymore
3. Rotate back to portrait
4. Scrolling works fine

### Is there any code involved? 
Here is a minimal reproduction of the issue in Angular:
https://stackblitz.com/edit/nativescript-stackblitz-templates-72gv44?file=src%2Fapp%2Fapp.component.html,package.json&title=NativeScript%20Starter%20Angular

Thank you for the amazing plugins! If I had more time than I currently do, I'd love to dig into some of these issues and contribute.

**Comment by farfromrefug** [comment]
@hendrickson-tyler thought I had fixe this ! I ll try to reproduce it. If I can't I might ask you for an exame closer to your production app.

**Comment by farfromrefug** [comment]
@hendrickson-tyler can you try latest version? should be fixed

**Comment by hendrickson-tyler** [comment]
@farfromrefug Awesome, looks like that did the trick! Thank you so much for the quick turnaround!
