### ISSUE TITLE
Doesn't work with Vue3

### ISSUE THREAD

**Issue by tralves** [nativescript-community/ui-drawer#23]
### Please, tell us how to recreate the issue in as much detail as possible. 
I spent some time trying to implement support for Vue3.

Here's my attempt: https://github.com/tralves/ui-drawer/tree/add-vue3-support
I was heavily inspired on `SwipeMenu`'s implementation, but it doesn't work.

I can see that my `Drawer` component (https://github.com/tralves/ui-drawer/blob/add-vue3-support/src/ui-drawer/vue3/component.ts) is created but not the `NativeDrawer` component (https://github.com/tralves/ui-drawer/blob/add-vue3-support/src/ui-drawer/vue3/index.ts)

If anyone know the solution or wants to try themselves, I'd be very thankful.

Thanks!

**Comment by tralves** [comment]
It works now! See PR: https://github.com/nativescript-community/ui-drawer/pull/24

It works well. The examples all run. There are some things I couldn't quite understand:

1- It is using the wrapper component `src/ui-drawer/vue3/component.ts`. The exported methods don't work (they cause an infinite loop). Instead, I am just calling the `open` and `close` methods directly on the `nativeView` (e.g. `this.$refs['drawer'].nativeView.open(side);`). I have a feeling I saw this happening before in another plugin...

2- For some reason these methods don't work if called from a function registered in setup() or <script setup>. The methods in the base component run and the [`animateToPosition`](https://github.com/tralves/ui-drawer/blob/9296d864841685a1f0f43204ff36f20d3e5fd971/src/ui-drawer/index.ts#L897) is called, but nothing happens. Dragging still works, though.

**Comment by PixsaOJ** [comment]
I use `toggle` because it does not cause double click issues.
