### ISSUE TITLE
Not working after dependency update.

### ISSUE THREAD

**Issue by ondrejlohnisky** [nativescript-community/ui-drawer#30]
It seems not working after https://github.com/nativescript-community/gesturehandler latest commit.

**Comment by farfromrefug** [comment]
@ondrejlohnisky what do you mean by not working? can you share an error log?

**Comment by ondrejlohnisky** [comment]
False alarm, I don't know what was wrong... after I was working on something else it magically started working correctly.
Anyway, thx for fast reaction.
closed

**Comment by ondrejlohnisky** [comment]
False alarm, I don't know what was wrong... after I was working on something else it magically started working correctly.
Anyway, thx for fast reaction.
closed
