### ISSUE TITLE
Angular build fails with latest version 0.1.28 

### ISSUE THREAD

**Issue by sublime392** [nativescript-community/ui-drawer#32]
Updating to version 0.1.28 results in following build error. Pinning to version 0.1.27 is a temporary workaround.

ERROR in ../../node_modules/@nativescript-community/ui-drawer/angular/fesm2022/nativescript-community-ui-drawer-angular.mjs 58:60-81
export 'ɵsetClassDebugInfo' (imported as 'i0') was not found in '@angular/core'

**Comment by farfromrefug** [comment]
@sublime392 i built it with angular 17. Maybe you need to upgrade angular?

**Comment by sublime392** [comment]
@farfromrefug sorry, I didn't think about the fact that I was in my master branch which is still on Angular 15. Works fine on Angular 17.
