### ISSUE TITLE
all NS project in my computer stop working with message - Error: spawn EINVAL

### ISSUE THREAD

**Issue by AAlex-11** [nativescript-community/ui-drawer#34]
There are old project in my computer, based on community-drawer, I don't touch it during a couple month. Project was worked a couple month ago. Today I try to start it and found that project full dead.

![NS-06082024_171742_1](https://github.com/nativescript-community/ui-drawer/assets/138773344/dcd1034b-a2f5-4510-9149-926a4b24d776)
[drawerProject.log](https://github.com/user-attachments/files/15748342/drawerProject.log)

I have my current project what worked before I try to update Angular and Node in my computer, this is config of my current project

       {
       "name": "MyVault",
       "main": "./src/main.ts",
       "version": "1.0.0",
       "private": true,
       "dependencies": {
           "@angelengineering/filepicker": "^1.2.0",
           "@angular-devkit/architect": "^0.1800.3",
           "@angular-devkit/core": "^18.0",
           "@angular/animations": "^18.0",
           "@angular/common": "^18.0",
           "@angular/compiler": "^18.0",
           "@angular/core": "^18.0",
           "@angular/forms": "^18.0",
           "@angular/platform-browser": "^18.0",
           "@angular/platform-browser-dynamic": "^18.0",
           "@angular/router": "^18.0",
           "@nativescript-community/arraybuffers": "^1.1.5",
           "@nativescript-community/perms": "^2.3.3",
           "@nativescript-community/ui-checkbox": "^2.0.12",
           "@nativescript-community/ui-drawer": "^0.1.27",
           "@nativescript-community/ui-svg": "^0.1.33",
           "@nativescript/angular": "^18.0",
           "@nativescript/core": "~8.6.0",
           "@nativescript/secure-storage": "^3.0.3",
           "@nativescript/theme": "~3.0.2",
           "nativescript-android-fs": "^1.3.0",
           "nativescript-clipboard": "^2.1.1",
           "npm": "^10.8.1",
           "platform": "^1.3.6",
           "rxjs": "~7.8.0",
           "zone.js": "~0.13.0"
       },
       "devDependencies": {
           "@angular-devkit/build-angular": "^18.0",
           "@angular/cli": "^18.0.3",
           "@angular/compiler-cli": "^18.0",
           "@nativescript/android": "^8.6.2",
           "@nativescript/preview-cli": "^1.0.13",
           "@nativescript/types": "^8.6.0",
           "@nativescript/webpack": "^5.0.18",
           "@ngtools/webpack": "^18.0",
           "@types/platform": "^1.3.6",
           "typescript": "^5.1.6"
       },
       "readme": "MyVault"
       }

On this project I try to upgrade Angular to latest version, because Drawer destroyed current project

![MyVault-06062024_235654](https://github.com/nativescript-community/ui-drawer/assets/138773344/16c93d34-b275-4877-af28-50b695b33e0d)

my update command was just update Angular 

                npm install --save-dev @angular/cli@latest --force

after that project full dead, this is log 
[nsBuildLog-1.txt](https://github.com/user-attachments/files/15748361/nsBuildLog-1.txt)

all versions in working project looks as latest

        node -v                                                                                                                                                                                          
        v22.2.0
        ng version
        Angular CLI: 18.0.3
        Node: 22.2.0
        Package Manager: npm 10.8.1
        OS: win32 x64
        Angular: 18.0.2
        ... animations, common, compiler, compiler-cli, core, forms
        ... platform-browser, platform-browser-dynamic, router
        Package                         Version
        ---------------------------------------------------------
        @angular-devkit/architect       0.1800.3
        @angular-devkit/build-angular   18.0.3
        @angular-devkit/core            18.0.3
        @angular-devkit/schematics      18.0.3
        @angular/cli                    18.0.3
        @ngtools/webpack                18.0.3
        @schematics/angular             18.0.3
        rxjs                            7.8.1
        typescript                      5.4.5
        zone.js                         0.13.3

in project with workable drawer demo

       ng version      
       Angular CLI: 18.0.3
       Node: 22.2.0
       Package Manager: npm 10.8.1
       OS: win32 x64
       Angular: 16.2.12
       ... animations, common, compiler, compiler-cli, core, forms
       ... platform-browser, platform-browser-dynamic, router
       Package                         Version
       ---------------------------------------------------------
       @angular-devkit/architect       0.1602.13
       @angular-devkit/build-angular   16.2.13
       @angular-devkit/core            16.2.13
       @angular-devkit/schematics      18.0.3 (cli-only)
       @ngtools/webpack                16.2.13
       @schematics/angular             18.0.3 (cli-only)
       rxjs                            7.8.1
       typescript                      5.1.6
       zone.js                         0.13.3
    
I don't understand what happens with my NS projects, why they stop working and what does message means:

      Error: spawn EINVAL
            at Errors.failWithOptions (C:\Users\Razen\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:157:27)
            at Errors.fail (C:\Users\Razen\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:130:21)
            at GradleCommandService.<anonymous> (C:\Users\Razen\AppData\Roaming\npm\node_modules\nativescript\lib\services\android\gradle-command-service.js:39:30)
            at Generator.throw (<anonymous>)
            at rejected (C:\Users\Razen\AppData\Roaming\npm\node_modules\nativescript\lib\services\android\gradle-command-service.js:6:65)

Two full logs of failed grade process applied.

**Comment by rigor789** [comment]
https://github.com/NativeScript/NativeScript/issues/10532

**Comment by AAlex-11** [comment]
Thank, you. This trouble fixed.
